language: csharp

dotnet: 5.0.100
mono: none
sudo: false

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: true
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

script:
    - dotnet build Tournament.Contracts.sln -c Release

after_script:
    - bash <(curl -s https://codecov.io/bash)