version: 0.2.{build}-alpha
image: Visual Studio 2022
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
before_build:
  - dotnet restore
build:
  verbosity: normal
after_build:
  - dotnet pack Tournament.Contracts -v=n /p:Configuration=Release /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**\*.nupkg'
  name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: E6iV/0EWXnyFgOzUzukLUvyrGzfbwUVPkPS/D3mYRW1+PF9LzF0SW10RVH7uskOH
  artifact: /.*\.nupkg/
  on:
    branch: 0.2